rm openLocation.xpm
rm printPageSetupDialog.xpm
rm CustomizeToolbarWindow.xpm
rm commonDialog.xpm
rm SanitizeDialog.xpm
rm places.xpm
rm migrationWizard.xpm
rm wizard.xpm
rm viewSource.xpm
rm winInspectormain.xpm
rm BrowserPreferences.xpm
rm PermissionsDialog.xpm
rm AdvancedJSDialog.xpm
rm FontsDialog.xpm
rm ColorsDialog.xpm
rm LanguagesDialog.xpm
rm CookiesDialog.xpm
rm SignonViewerExceptionDialog.xpm
rm SignonViewerDialog.xpm
rm ConnectionsDialog.xpm
rm history.xpm
rm certmanager.xpm
rm crlviewer.xpm
rm OCSPDialog.xpm
rm devicemanager.xpm
rm aboutDialog.xpm
rm engineManager.xpm
