copy main-window.ico     openLocation.ico
copy main-window.ico     printPageSetupDialog.ico
copy main-window.ico     CustomizeToolbarWindow.ico
copy main-window.ico     commonDialog.ico
copy main-window.ico     SanitizeDialog.ico
copy bookmark-window.ico places.ico
copy import-window.ico   migrationWizard.ico
copy main-window.ico     wizard.ico
copy url-file.ico        viewSource.ico
copy findDialog.ico      winInspectorMain.ico
copy import-window.ico   BrowserPreferences.ico
copy import-window.ico   PermissionsDialog.ico
copy import-window.ico   AdvancedJSDialog.ico
copy import-window.ico   FontsDialog.ico
copy import-window.ico   ColorsDialog.ico
copy import-window.ico   LanguagesDialog.ico
copy import-window.ico   CookiesDialog.ico
copy import-window.ico   SignonViewerExceptionDialog.ico
copy import-window.ico   SignonViewerDialog.ico
copy import-window.ico   ConnectionsDialog.ico
copy import-window.ico   history.ico
copy import-window.ico   certmanager.ico
copy import-window.ico   crlviewer.ico
copy import-window.ico   OCSPDialog.ico
copy import-window.ico   devicemanager.ico
copy main-window.ico     aboutDialog.ico
copy main-window.ico     engineManager.ico