cp main-window.xpm     openLocation.xpm
cp main-window.xpm     printPageSetupDialog.xpm
cp main-window.xpm     CustomizeToolbarWindow.xpm
cp main-window.xpm     commonDialog.xpm
cp main-window.xpm     SanitizeDialog.xpm
cp bookmark-window.xpm places.xpm
cp import-window.xpm   migrationWizard.xpm
cp main-window.xpm     wizard.xpm
cp url-file.xpm        viewSource.xpm
cp findDialog.xpm      winInspectorMain.xpm
cp import-window.xpm   BrowserPreferences.xpm
cp import-window.xpm   PermissionsDialog.xpm
cp import-window.xpm   AdvancedJSDialog.xpm
cp import-window.xpm   FontsDialog.xpm
cp import-window.xpm   ColorsDialog.xpm
cp import-window.xpm   LanguagesDialog.xpm
cp import-window.xpm   CookiesDialog.xpm
cp import-window.xpm   SignonViewerExceptionDialog.xpm
cp import-window.xpm   SignonViewerDialog.xpm
cp import-window.xpm   ConnectionsDialog.xpm
cp import-window.xpm   history.xpm
cp import-window.xpm   certmanager.xpm
cp import-window.xpm   crlviewer.xpm
cp import-window.xpm   OCSPDialog.xpm
cp import-window.xpm   devicemanager.xpm
cp main-window.xpm     aboutDialog.xpm
cp main-window.xpm     engineManager.xpm